# Generated by Django 3.1.4 on 2020-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0002_auto_20201216_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punishment',
            name='url',
        ),
        migrations.AlterField(
            model_name='level',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
